### ISSUE TITLE
Social Titles not aligned

### ISSUE THREAD

**Issue by SLiCK-303** [thirtybees/niara#4]
When you create a new user in the FO, the titles do not align.  The first is out of line with the others.
![Capture](https://user-images.githubusercontent.com/763426/60131745-afe1aa00-975f-11e9-8570-d9baa88af625.PNG)

**Comment by SLiCK-303** [comment]
You see this when you edit your profile in the FO as well.

**Comment by SLiCK-303** [comment]
I don't know if its the 'proper' fix, but if you change line 2123 in global.css
from:
  vertical-align: middle;
to:
  vertical-align: baseline;
it seems to fix it.

**Comment by Dh42** [comment]
Try this commit, https://github.com/thirtybees/niara/commit/20948850e2014dbef84c3e4d919fc8fc6a15b56d 

Since the global.css is compiled I just put an override and re-compiled it. It might not be the most elegant, I am sure there is some reason why they did that, but I could not find a place where it breaks. 

https://i.imgur.com/yfKkTDv.png

**Comment by SLiCK-303** [comment]
It's fixed.....nice job as always
